server:
  port: 8085
eureka:
  instance:
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:8086/eureka
spring:
  application:
    name: zuul
management:
  endpoints:
    web:
      exposure:
        include: routes
zuul:
  ignored-services: "*"
  routes:
    service-hi: "/service/**"
  prefix: /api
service-hi:
  ribbon:
    ReadTimeout: 5000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

