server:
  port: 8090
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8086/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
  server:
    eviction-interval-timer-in-ms: 10000
spring:
  application:
    name: service-fei